### ISSUE TITLE
Layout issue on WatchOS 

### ISSUE THREAD

**Issue by zimsneexh** [AcaciaLinux/website_old#2]
By always displaying the sidebar the website becomes unusable on watchOS.

**Comment by maxkofler** [comment]
We're looking into it

**Comment by zimsneexh** [comment]
ETA when? Major issue on my end. Please fix asap

**Comment by maxkofler** [comment]
ETA = Maybe in 1 Year, may be 10 Years too

**Comment by zimsneexh** [comment]
frechheit

**Comment by zimsneexh** [comment]
Still a major issue. Don't close.

**Comment by maxkofler** [comment]
Dont' f**ing care

**Comment by zimsneexh** [comment]
Reported for being toxic.

**Comment by zimsneexh** [comment]
still hin please fix

**Comment by maxkofler** [comment]
Fixed on new repo `website-ng`
